#!/bin/bash -ex

# This script is expect to run in the working directory the root of the git repository.

STAGING_PRODUCT=$1
UPDATE_PRODUCT=$2
OS=$3
WS=$4
ARCH=$5

# You can test another OS manually by changing this.
# OS=linux
# WS=gtk

#  Operate on different file extensions and different way of extract that content depend on the OS.
#
if [[ $OS == 'win32' ]]; then
SUFFIX="zip"
UNPACK="unzip -q"
else
SUFFIX="tar.gz"
UNPACK="tar -xvf"
fi

# Extract these values from the parent POM.
#
SIMREL_VERSION=$(sed -nE '1,$s%.*<RELEASE_NAME>(.*)</RELEASE_NAME>.*%\1%p' releng/org.eclipse.epp.config/parent/pom.xml)
SIMREL_PREVIOUS_VERSION=$(sed -nE '1,$s%.*<PREV_RELEASE_NAME>(.*)</PREV_RELEASE_NAME>.*%\1%p' releng/org.eclipse.epp.config/parent/pom.xml)
MILESTONE=$(sed -nE '1,$s%.*<RELEASE_MILESTONE>(.*)</RELEASE_MILESTONE>.*%\1%p' releng/org.eclipse.epp.config/parent/pom.xml)

# Show what we're operating upon.
#
echo "STAGING_PRODUCT=$STAGING_PRODUCT, UPDATE_PRODUCT=$UPDATE_PRODUCT, SIMREL_VERSION=$SIMREL_VERSION, MILESTONE=$MILESTONE, OS=$OS, WS=$WS, ARCH=$ARCH, SUFFIX=$SUFFIX, UNPACK='$UNPACK'"

# Clean up the entire folder in which we extract content.
#

rm -rf sanity-check

##################################################################
# The staging product to test
##################################################################

# The names are a bit inconsistent for Windows presumably because there is on one windowing system.
#
STAGING_PRODUCT_NAME=$(echo "eclipse-$STAGING_PRODUCT-$SIMREL_VERSION-$MILESTONE-$OS-$WS-$ARCH.$SUFFIX" | sed 's/win32-win32-/win32-/')

mkdir -p sanity-check/staging-$STAGING_PRODUCT
cd sanity-check/staging-$STAGING_PRODUCT
curl -O "https://download.eclipse.org/technology/epp/staging/$STAGING_PRODUCT_NAME"
$UNPACK $STAGING_PRODUCT_NAME

cd -

##################################################################
# Update product from previous version to test for updating to current version
##################################################################

# The names are a bit inconsistent for Windows presumably because there is on one windowing system.
#
UPDATE_PRODUCT_NAME=$(echo "eclipse-$UPDATE_PRODUCT-$SIMREL_PREVIOUS_VERSION-R-$OS-$WS-$ARCH.$SUFFIX" | sed 's/win32-win32-/win32-/')

mkdir -p sanity-check/update-$UPDATE_PRODUCT
cd sanity-check/update-$UPDATE_PRODUCT
curl -O "https://download.eclipse.org/technology/epp/downloads/release/$SIMREL_PREVIOUS_VERSION/R/$UPDATE_PRODUCT_NAME"
$UNPACK $UPDATE_PRODUCT_NAME

# Set the repository preferences for updating the old release to the current staging repositories.
#
for i in $(find eclipse -name "org.eclipse.equinox.p2.*.repository.prefs"); do
echo "Update preferences: $i"
cat >> $i << EOF

repositories/https\:__download.eclipse.org_justj_epp_milestone_latest/enabled=true
repositories/https\:__download.eclipse.org_justj_epp_milestone_latest/isSystem=false
repositories/https\:__download.eclipse.org_justj_epp_milestone_latest/nickname=JustJ EPP Milestone Latest
repositories/https\:__download.eclipse.org_justj_epp_milestone_latest/uri=https\://download.eclipse.org/justj/epp/milestone/latest/

repositories/https\:__download.eclipse.org_staging_$SIMREL_VERSION/enabled=true
repositories/https\:__download.eclipse.org_staging_$SIMREL_VERSION/isSystem=false
repositories/https\:__download.eclipse.org_staging_$SIMREL_VERSION/nickname=SimRel Staging $SIMREL_VERSION
repositories/https\:__download.eclipse.org_staging_$SIMREL_VERSION/uri=https\://download.eclipse.org/staging/$SIMREL_VERSION/

repositories/https\:__download.eclipse.org_technology_epp_staging_repository/enabled=true
repositories/https\:__download.eclipse.org_technology_epp_staging_repository/isSystem=false
repositories/https\:__download.eclipse.org_technology_epp_staging_repository/nickname=EPP Staging $SIMREL_VERSION
repositories/https\:__download.eclipse.org_technology_epp_staging_repository/uri=https\://download.eclipse.org/technology/epp/staging/repository/

EOF

done

cd -