name: Build EPP

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        package:
          - committers
          - cpp
          - dsl
          - embedcpp
          - java
          - jee
          - modeling
          - php
          - rcp
          - scout
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.9
    - name: Build with Maven
      run: mvn clean verify -B -Pepp.p2.${{ matrix.package }} -Pepp.product.${{ matrix.package }} -Pepp.p2.common
    - name: Upload bundle information
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: bundles.info for ${{ matrix.package }}
        path: '**/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info'
