name: Build EPP

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        package:
          - committers
          - cpp
          - dsl
          - embedcpp
          - java
          - jee
          - modeling
          - parallel
          - php
          - rcp
          - scout
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.9.2
    - name: Build with Maven
      run: mvn clean verify -Pepp.package.${{ matrix.package }}
    - name: Upload bundle information
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: bundles.info for ${{ matrix.package }}
        path: '**/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info'
